
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: {
        default: "Buy MLBB Diamonds India – Cheapest MLBB Topup | mlbbtopup.in",
        template: "%s | Buy MLBB Diamonds India – Cheapest MLBB Topup",
    },
    description:
        "Instant MLBB diamond recharge in India. Cheapest rates, safe payment, fast delivery. Weekly pass & small packs available.",
    keywords: [
        "mlbb recharge india cheap",
        "mlbb top up india instant",
        "buy ml diamonds india low price",
        "mlbb recharge with upi",
        "cheapest mlbb recharge website",
        "mlbb recharge trusted site india",
        "mlbb diamonds instant delivery india",
        "mobile legends recharge india fast",
        "mlbb top up india no login",
        "mlbb recharge website india cheap",
        "mlbb topup",
        "mlbb diamond topup",
        "mlbb diamond recharge",
        "buy mlbb diamonds",
        "mobile legends topup",
        "mlbb diamonds india",
        "mlbb recharge under 50 rs",
        "mlbb recharge under 80 rs india",
        "mlbb recharge under 100 rs india",
        "cheap mlbb diamonds 2024 india",
        "lowest price mlbb diamonds india",
        "mlbb diamond price list india",
        "mlbb recharge best price india",
        "mlbb diamond rate india today",
        "mlbb topup discount india",
        "mlbb recharge offer india today",
        "buy 86 diamonds mlbb india",
        "buy 172 diamonds mlbb india",
        "mlbb weekly pass recharge india",
        "mlbb twilight pass recharge india",
        "mlbb small diamond pack india",
        "mlbb mini pack recharge instant",
        "mlbb weekly pass cheapest india",
        "mlbb diamond bundle recharge india",
        "mlbb subscription recharge india",
        "mlbb starlight recharge india",
        "mlbb recharge by uid india",
        "mlbb topup uid only india",
        "instant mlbb recharge without login",
        "mlbb auto topup website india",
        "mlbb instant diamonds delivery",
        "fastest mlbb recharge india",
        "mlbb recharge in seconds india",
        "mlbb topup instant payment india",
        "mlbb recharge direct account india",
        "legit mlbb recharge india",
        "trusted mlbb diamond seller india",
        "safe mlbb topup site india",
        "real mlbb recharge website india",
        "genuine mlbb diamond store india",
        "secure mlbb recharge with upi",
        "verified mlbb topup website",
        "best site to buy mlbb diamonds india",
        "how to buy mlbb diamonds with upi",
        "mlbb recharge guide india",
        "mlbb diamond recharge steps",
        "mobile legends payment methods india",
        "how instant mlbb topup works",
        "mlbb weekly pass worth it india",
        "mlbb cheapest recharge method india",
        "mlbb topup without moonton login",
    ],
    metadataBase: new URL("https://mlbbtopup.in"),
    openGraph: {
        title: "Buy MLBB Diamonds India – Cheapest MLBB Topup | mlbbtopup.in",
        description:
            "Instant MLBB diamond recharge in India. Cheapest rates, safe payment, fast delivery. Weekly pass & small packs available.",
        url: "https://mlbbtopup.in",
        siteName: "mlbbtopup.in",
        type: "website",
    },
    robots: {
        index: true,
        follow: true,
    },
};
